
#ifndef ConnectionsManagerErrors_h
	#define ConnectionsManagerErrors_h

	#include "Error.h"
	#include <iostream>

	enum ConnectionsManagerErrorsCodes {

		// ConnectionsManagerService
		CM_CONNECTIONSMANAGERSERVICE_ONINITEVENTSSET_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONFINISHEVENTSSET_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONINITPROCESSORS_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONFINISHPROCESSORS_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONSTARTPROCESSORS_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONWAITPROCESSORS_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONCANCELPROCESSORS_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONSTARTMYTIMES_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_ONSTOPMYTIMES_FAILED,
		CM_CONNECTIONSMANAGERSERVICE_SIGNALRECEIVED,

		// CMProcessor
		CM_CMPROCESSOR_INIT_FAILED,
		CM_CMPROCESSOR_FINISH_FAILED,
		CM_CMPROCESSOR_SETISSHUTDOWN_FAILED,
		CM_CMPROCESSOR_GETISSHUTDOWN_FAILED,
		CM_CMPROCESSOR_PROCESSEVENT_FAILED,
		CM_CMPROCESSOR_HANDLECONNECTIONTOACCEPTEVENT_FAILED,
		CM_CMPROCESSOR_HANDLECONNECTIONREADYTOREADEVENT_FAILED,
		CM_CMPROCESSOR_HANDLECHECKSOCKETSPOOLEVENT_FAILED,
		CM_CMPROCESSOR_HANDLECHECKUNUSEDSOCKETSEVENT_FAILED,
		CM_CMPROCESSOR_PROCESSRECEIVEDREQUEST_FAILED,
		CM_CMPROCESSOR_EVENTUNKNOWN,
		CM_CMPROCESSOR_NOTFOUNDSESSIONFREE,
		CM_CMPROCESSOR_ALREADYANSWEREDTOCLIENT,
		CM_CMPROCESSOR_READREQUESTWITHOUTBODY,
		CM_CMPROCESSOR_TOOTIMETOACCEPTANDREAD,
		CM_CMPROCESSOR_TTLSOCKETEXPIRED,
		CM_CMPROCESSOR_SOCKETSEXPIRED,
		CM_CMPROCESSOR_TOOMANYTIMETOMANAGETHEEVENT,
		CM_CMPROCESSOR_NOTOBEPROXIED,
		CM_CMSPROCESSOR_WRONGURIFORMAT,
		CM_CMPROCESSOR_DELETEONFREESESSIONSFAILED,
		CM_CMPROCESSOR_INSERTONFREESESSIONSFAILED,

		// CheckSocketsPoolTimes
		CM_CHECKSOCKETSPOOLTIMES_INIT_FAILED,
		CM_CHECKSOCKETSPOOLTIMES_FINISH_FAILED,
		CM_CHECKSOCKETSPOOLTIMES_REACHEDMAXIMUMEVENTSTOALLOCATE,

		// CheckServerSocketTimes
		CM_CHECKSERVERSOCKETTIMES_INIT_FAILED,
		CM_CHECKSERVERSOCKETTIMES_FINISH_FAILED,
		CM_CHECKSERVERSOCKETTIMES_REACHEDMAXIMUMEVENTSTOALLOCATE,

		// CheckUnusedSocketsTimes
		CM_CHECKUNUSEDSOCKETSTIMES_INIT_FAILED,
		CM_CHECKUNUSEDSOCKETSTIMES_FINISH_FAILED,
		CM_CHECKUNUSEDSOCKETSTIMES_REACHEDMAXIMUMEVENTSTOALLOCATE,

		// ConnectionEvent
		CM_CONNECTIONEVENT_INIT_FAILED,
		CM_CONNECTIONEVENT_FINISH_FAILED,
		CM_CONNECTIONEVENT_GETCONNECTIONINFORMATION_FAILED,
		CM_CONNECTIONEVENT_CONNECTIONINFORMATIONNOTINITIALIZED,

		// Session
		CM_SESSION_INIT_FAILED,
		CM_SESSION_FINISH_FAILED,
		CM_SESSION_RESET_FAILED,
		CM_SESSION_ACCEPTCONNECTION_FAILED,
		CM_SESSION_RELEASECONNECTION_FAILED,
		CM_SESSION_WRITERESPONSE_FAILED,
		CM_SESSION_READREQUEST_FAILED,
		CM_SESSION_NOTCONNECTIONTOACCEPT_FAILED,
		CM_SESSION_RESPONSENOTSENTBECAUSEOLDSOCKET,
		CM_SESSION_REQUESTNOTREADBECAUSEOLDSOCKET,
		CM_SESSION_CONNECTIONFAILED,
		CM_SESSION_ADDSOCKETFAILED,
		CM_SESSION_DELETESOCKETFAILED,
		CM_SESSION_FINDOLDCONNECTION,

		// CMSocketsPool
		CM_CMSOCKETSPOOL_EXCEPTIONONSOCKET,

		// HTTPProxyThread
		CM_HTTPPROXYTHREAD_INIT_FAILED,
		CM_HTTPPROXYTHREAD_FINISH_FAILED,
		CM_HTTPPROXYTHREAD_SENDERRORTOHTTPCLIENT_FAILED,
		CM_HTTPPROXYTHREAD_HTTPGETINTERNALERROR,

		// common
		CM_ACTIVATION_WRONG,
		CM_CONFIGITEMWRONG,
		CM_WRONGSOAPMETHODCONFIGURATION,
		CM_SSCANF_FAILED,
		CM_NEW_FAILED,

		// Insert here other errors...

		CM_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long',
		// possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (ConnectionsManagerErrors, CM_MAXERRORS)
   
#endif

