/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#ifndef ConfigurationErrors_h
	#define ConfigurationErrors_h

	#include "Error.h"
	#include "iostream"


	/**
		Click <a href="ConfigurationErrors.C#ConfigurationErrors" target=classContent>here</a> for the errors strings.
	*/
	enum ConfigurationErrorsCodes {

		// ConfigurationItem
		CFG_CONFIGURATIONITEM_INIT_FAILED,
		CFG_CONFIGURATIONITEM_INSERTITEMVALUE_FAILED,
		CFG_CONFIGURATIONITEM_APPENDITEMVALUE_FAILED,
		CFG_CONFIGURATIONITEM_GETISCASESENSITIVE_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMNAME_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMNAMELENGTH_FAILED,
		CFG_CONFIGURATIONITEM_MODIFYITEMNAME_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMCOMMENT_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMCOMMENTLENGTH_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMVALUESNUMBER_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMVALUE_FAILED,
		CFG_CONFIGURATIONITEM_GETITEMVALUELENGTH_FAILED,
		CFG_CONFIGURATIONITEM_MODIFYITEMVALUE_FAILED,
		CFG_CONFIGURATIONITEM_MODIFYITEMCOMMENT_FAILED,
		CFG_CONFIGURATIONITEM_FINISH_FAILED,
		CFG_CONFIGURATIONITEM_WRITE_FAILED,
		CFG_CONFIGURATIONITEM_COPY_FAILED,
		CFG_CONFIGURATIONITEM_BUFFERTOOSHORT,
		CFG_CONFIGURATIONITEM_WRONGCFGVALUE,

		// ConfigurationSection
		CFG_CONFIGURATIONSECTION_INIT_FAILED,
		CFG_CONFIGURATIONSECTION_APPENDCFGITEM_FAILED,
		CFG_CONFIGURATIONSECTION_GETISCASESENSITIVE_FAILED,
		CFG_CONFIGURATIONSECTION_GETSECTIONNAME_FAILED,
		CFG_CONFIGURATIONSECTION_GETSECTIONNAMELENGTH_FAILED,
		CFG_CONFIGURATIONSECTION_MODIFYSECTIONNAME_FAILED,
		CFG_CONFIGURATIONSECTION_GETSECTIONCOMMENT_FAILED,
		CFG_CONFIGURATIONSECTION_GETSECTIONCOMMENTLENGTH_FAILED,
		CFG_CONFIGURATIONSECTION_MODIFYSECTIONCOMMENT_FAILED,
		CFG_CONFIGURATIONSECTION_GETSECTIONDATE_FAILED,
		CFG_CONFIGURATIONSECTION_MODIFYSECTIONDATE_FAILED,
		CFG_CONFIGURATIONSECTION_GETCFGITEMSNUMBER_FAILED,
		CFG_CONFIGURATIONSECTION_GETCFGITEMBYNAME_FAILED,
		CFG_CONFIGURATIONSECTION_GETPTRCFGITEMBYNAME_FAILED,
		CFG_CONFIGURATIONSECTION_GETCFGITEMBYINDEX_FAILED,
		CFG_CONFIGURATIONSECTION_FINISH_FAILED,
		CFG_CONFIGURATIONSECTION_WRITE_FAILED,
		CFG_CONFIGURATIONSECTION_COPY_FAILED,
		CFG_ITEM_NOTFOUND,
		CFG_CONFIGURATIONSECTIONDATE_NOTFOUND,

		// Config
		CFG_CONFIG_INIT_FAILED,
		CFG_CONFIG_REMOVECFGSECTION_FAILED,
		CFG_CONFIG_APPENDCFGSECTION_FAILED,
		CFG_CONFIG_APPENDITEMVALUE_FAILED,
		CFG_CONFIG_MODIFYITEMCOMMENT_FAILED,
		CFG_CONFIG_MODIFYSECTIONCOMMENT_FAILED,
		CFG_CONFIG_GETISCASESENSITIVE_FAILED,
		CFG_CONFIG_GETCONFIGNAME_FAILED,
		CFG_CONFIG_MODIFYCONFIGNAME_FAILED,
		CFG_CONFIG_GETSECTIONSNUMBER_FAILED,
		CFG_CONFIG_GETCFGSECTIONBYINDEX_FAILED,
		CFG_CONFIG_GETCFGSECTIONBYNAME_FAILED,
		CFG_CONFIG_GETCFGITEMBYINDEX_FAILED,
		CFG_CONFIG_GETCFGITEMBYNAME_FAILED,
		CFG_CONFIG_GETITEMVALUESNUMBER_FAILED,
		CFG_CONFIG_GETITEMVALUE_FAILED,
		CFG_CONFIG_MODIFYITEMVALUE_FAILED,
		CFG_CONFIG_FINISH_FAILED,
		CFG_CONFIG_WRITE_FAILED,
		CFG_CONFIG_COPY_FAILED,
		CFG_CONFIG_GETITEMSNUMBER_FAILED,
		CFG_SECTION_NOTFOUND,

		// common
		CFG_NEW_FAILED,
		CFG_NOTIMPLEMENTED_FAILED,
		CFG_ACTIVATION_WRONG,
		CFG_OPERATIONNOTALLOWED,
		CFG_ENCRYPT_FAILED,
		CFG_DECRYPT_FAILED,

		// Insert here other errors...

		CFG_MAXERRORS
	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long', possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (ConfigurationErrors, CFG_MAXERRORS)

#endif

