/*
 Copyright (C) Giuliano Catrambone (giuliano.catrambone@catrasoftware.it)

 This program is free software; you can redistribute it and/or 
 modify it under the terms of the GNU General Public License 
 as published by the Free Software Foundation; either 
 version 2 of the License, or (at your option) any later 
 version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

 Commercial use other than under the terms of the GNU General Public
 License is allowed only after express negotiation of conditions
 with the authors.
*/


#ifndef ToolsErrors_h
	#define ToolsErrors_h

	#include "Error.h"
	#include <iostream>


	//
	// Defined errors:
	//   
   
	enum ToolsErrorsCodes {

		// Buffer
		TOOLS_BUFFER_INIT_FAILED,
		TOOLS_BUFFER_FINISH_FAILED,
		TOOLS_BUFFER_GETBUFFER_FAILED,
		TOOLS_BUFFER_GETBUFFERLENGTH_FAILED,
		TOOLS_BUFFER_SETBUFFER_FAILED,
		TOOLS_BUFFER_READBUFFERFROMFILE_FAILED,
		TOOLS_BUFFER_WRITEBUFFERONFILE_FAILED,
		TOOLS_BUFFER_STARTWITH_FAILED,
		TOOLS_BUFFER_ISEQUALWITH_FAILED,
		TOOLS_BUFFER_APPEND_FAILED,
		TOOLS_BUFFER_INSERTAT_FAILED,
		TOOLS_BUFFER_ALLOCMEMORYBLOCKFORBUFFERIFNECESSARY_FAILED,
		TOOLS_BUFFER_SUBSTITUTE_FAILED,
		TOOLS_BUFFER_REMOVECTRLCHARACTERS_FAILED,
		TOOLS_BUFFER_REMOVECHAR_FAILED,
		TOOLS_BUFFER_TRUNCATESTARTINGFROM_FAILED,
		TOOLS_BUFFER_TRUNCATEIFBIGGER_FAILED,
		TOOLS_BUFFER_SETCHAR_FAILED,
		TOOLS_BUFFER_STRIP_FAILED,
		TOOLS_BUFFER_GETCHAR_FAILED,
		TOOLS_BUFFER_CONVERSIONFROMCHARTOWCHAR_FAILED,
		TOOLS_BUFFER_INDEXOUTOFRANGE,
		TOOLS_BUFFER_CHARNOTFOUND,

		// DateTime
		TOOLS_DATETIME_NOWUTCINMILLISECS_FAILED,
		TOOLS_DATETIME_NOWLOCALINMILLISECS_FAILED,
		TOOLS_DATETIME_NOWLOCALTIME_FAILED,
		TOOLS_DATETIME_GETTIMEZONEINFORMATION_FAILED,
		TOOLS_DATETIME_GET_TM_LOCALTIME_FAILED,
		TOOLS_DATETIME_CONVERTFROMLOCALTOUTC_FAILED,
		TOOLS_DATETIME_CONVERTFROMUTCTOLOCAL_FAILED,
		TOOLS_DATETIME_CONVERTFROMLOCALDATETIMETOLOCALINSECS_FAILED,
		TOOLS_DATETIME_ADDSECONDS_FAILED,
		TOOLS_DATETIME_ISLEAPYEAR_FAILED,
		TOOLS_DATETIME_GETLASTDAYOFMONTH_FAILED,
		TOOLS_DATETIME_CONVERTFROMUTCINSECONDSTOBREAKDOWNUTC_FAILED,

		// StringTokenizer
		TOOLS_STRINGTOKENIZER_INIT_FAILED,
		TOOLS_STRINGTOKENIZER_FINISH_FAILED,
		TOOLS_STRINGTOKENIZER_NEXTTOKEN_FAILED,
		TOOLS_STRINGTOKENIZER_COUNTTOKENS_FAILED,
		TOOLS_STRINGTOKENIZER_NOMORETOKEN,

		// FileIO
		TOOLS_FILEIO_GETFILENAMEFROMPATHFILENAME_FAILED,
		TOOLS_FILEIO_REPLACEUNSAFEFILENAMECHARS_FAILED,
		TOOLS_FILEIO_OPENDIRECTORY_FAILED,
		TOOLS_FILEIO_READDIRECTORY_FAILED,
		TOOLS_FILEIO_CLOSEDIRECTORY_FAILED,
		TOOLS_FILEIO_GETWORKINGDIRECTORY_FAILED,
		TOOLS_FILEIO_GZIP_FAILED,
		TOOLS_FILEIO_GETDIRECTORYENTRYTYPE_FAILED,
		TOOLS_FILEIO_CHANGEPERMISSION_FAILED,
		TOOLS_FILEIO_READLINK_FAILED,
		TOOLS_FILEIO_CREATEDIRECTORY_FAILED,
		TOOLS_FILEIO_REMOVEDIRECTORY_FAILED,
		TOOLS_FILEIO_GETFILETIME_FAILED,
		TOOLS_FILEIO_GETFILESIZEINBYTES_FAILED,
		TOOLS_FILEIO_ISFILEEXISTING_FAILED,
		TOOLS_FILEIO_ISDIRECTORYEXISTING_FAILED,
		TOOLS_FILEIO_GETFILESYSTEMINFO_FAILED,
		TOOLS_FILEIO_GETDIRECTORYUSAGE_FAILED,
		TOOLS_FILEIO_GETDIRECTORYSIZEINBYTES_FAILED,
		TOOLS_FILEIO_COPYFILE_FAILED,
		TOOLS_FILEIO_MOVEFILE_FAILED,
		TOOLS_FILEIO_MOVELINK_FAILED,
		TOOLS_FILEIO_MOVEDIRECTORY_FAILED,
		TOOLS_FILEIO_COPYDIRECTORY_FAILED,
		TOOLS_FILEIO_CREATELINK_FAILED,
		TOOLS_FILEIO_OPEN_FAILED,
		TOOLS_FILEIO_CLOSE_FAILED,
		TOOLS_FILEIO_TOUCHFILE_FAILED,
		TOOLS_FILEIO_REMOVE_FAILED,
		TOOLS_FILEIO_SEEK_FAILED,
		TOOLS_FILEIO_READCHARS_FAILED,
		TOOLS_FILEIO_WRITECHARS_FAILED,
		TOOLS_FILEIO_READBYTES_FAILED,
		TOOLS_FILEIO_WRITEBYTES_FAILED,
		TOOLS_FILEIO_READNETUNSIGNEDINT8BIT_FAILED,
		TOOLS_FILEIO_READNETUNSIGNEDINT16BIT_FAILED,
		TOOLS_FILEIO_READNETUNSIGNEDINT24BIT_FAILED,
		TOOLS_FILEIO_READNETUNSIGNEDINT32BIT_FAILED,
		TOOLS_FILEIO_READNETUNSIGNEDINT64BIT_FAILED,
		TOOLS_FILEIO_READNETFLOAT16BIT_FAILED,
		TOOLS_FILEIO_READNETFLOAT32BIT_FAILED,
		TOOLS_FILEIO_WRITENETUNSIGNEDINT8BIT_FAILED,
		TOOLS_FILEIO_WRITENETUNSIGNEDINT16BIT_FAILED,
		TOOLS_FILEIO_WRITENETUNSIGNEDINT24BIT_FAILED,
		TOOLS_FILEIO_WRITENETUNSIGNEDINT32BIT_FAILED,
		TOOLS_FILEIO_WRITENETUNSIGNEDINT64BIT_FAILED,
		TOOLS_FILEIO_WRITENETFLOAT16BIT_FAILED,
		TOOLS_FILEIO_WRITENETFLOAT32BIT_FAILED,
		TOOLS_FILEIO_READMP4DESCRIPTORSIZE_FAILED,
		TOOLS_FILEIO_WRITEMP4DESCRIPTORSIZE_FAILED,
		TOOLS_FILEIO_LOCKFILE_FAILED,
		TOOLS_FILEIO_UNLOCKFILE_FAILED,
		TOOLS_FILEIO_APPENDBUFFER_FAILED,
		TOOLS_FILEIO_DIRECTORYFILESFINISHED,
		TOOLS_FILEIO_FILENOTRELEASED,
		TOOLS_FILEIO_BUFFERTOOSMALL,
		TOOLS_FILEIO_WRONGSOURCEFILE,
		TOOLS_FILEIO_DIRECTORYNOTEXISTING,
		TOOLS_FILEIO_UNKNOWNFILETYPE,

		// FileReader
		TOOLS_FILEREADER_INIT_FAILED,
		TOOLS_FILEREADER_FINISH_FAILED,
		TOOLS_FILEREADER_WRITE_FAILED,
		TOOLS_FILEREADER_SEEK_FAILED,
		TOOLS_FILEREADER_SEEKBYSEARCH_FAILED,
		TOOLS_FILEREADER_READLINE_FAILED,
		TOOLS_FILEREADER_READCHARS_FAILED,
		TOOLS_FILEREADER_READBYTES_FAILED,
		TOOLS_FILEREADER_READNETUNSIGNEDINT8BIT_FAILED,
		TOOLS_FILEREADER_READNETUNSIGNEDINT16BIT_FAILED,
		TOOLS_FILEREADER_READNETUNSIGNEDINT24BIT_FAILED,
		TOOLS_FILEREADER_READNETUNSIGNEDINT32BIT_FAILED,
		TOOLS_FILEREADER_READNETUNSIGNEDINT64BIT_FAILED,
		TOOLS_FILEREADER_READNETFLOAT16BIT_FAILED,
		TOOLS_FILEREADER_READNETFLOAT32BIT_FAILED,
		TOOLS_FILEREADER_READMP4DESCRIPTORSIZE_FAILED,
		TOOLS_FILEREADER_REFRESHCACHEIFNECESSARY_FAILED,
		TOOLS_FILEREADER_READMORETHANCACHE_FAILED,
		TOOLS_FILEREADER_CACHESIZETOOLOW,
		TOOLS_FILEREADER_BUFFERTOOSMALL,
		TOOLS_FILEREADER_REACHEDENDOFFILE,
		TOOLS_FILEREADER_BUFFERNOTFOUND,

		// MergeSort
		TOOLS_MERGESORT_MERGESORTASCENDING_FAILED,
		TOOLS_MERGESORT_MERGESORTDESCENDING_FAILED,

		// Convert
		TOOLS_CONVERT_BINARYTOBASE16_FAILED,
		TOOLS_CONVERT_BASE16TOBINARY_FAILED,
		TOOLS_CONVERT_STRINGTOBASE16_FAILED,
		TOOLS_CONVERT_BASE16TOSTRING_FAILED,
	
		// Encrypt
		TOOLS_ENCRYPT_ENCRYPT_FAILED,
		TOOLS_ENCRYPT_DECRYPT_FAILED,
		TOOLS_ENCRYPT_GETCRYPTEDBUFFERLENGTH_FAILED,
		TOOLS_ENCRYPT_GETDECRYPTEDBUFFERLENGTH_FAILED,

		// System
		TOOLS_SYSTEM_GETHOSTNAME_FAILED,
		TOOLS_SYSTEM_GETHOMEDIRECTORY_FAILED,
		TOOLS_SYSTEM_BUFFERTOOSMALL,
		TOOLS_SYSTEM_ENVIRONMENTVARIABLENOTDEFINED,

		// ProcessUtility
		TOOLS_PROCESSUTILITY_GETCURRENTPROCESSIDENTIFIER_FAILED,
		TOOLS_PROCESSUTILITY_EXECUTE_FAILED,
		TOOLS_PROCESSUTILITY_SETUSERANDGROUPID_FAILED,
		TOOLS_PROCESSUTILITY_PROCESSDOESNOTEXITNORMALLY,
		TOOLS_PROCESSUTILITY_USERNAMENOTFOUND,

		// Network
		TOOLS_NETWORK_INIT_FAILED,
		TOOLS_NETWORK_FINISH_FAILED,
		TOOLS_NETWORK_PARSEIPADDRESS_FAILED,
		TOOLS_NETWORK_ISIPINNETWORK_FAILED,
		TOOLS_NETWORK_GETIPADDRESSFROMHOSTNAME,
		TOOLS_NETWORK_IPADDRESSNOTRETRIEVED,

		// Service
		TOOLS_SERVICE_LAUNCHUNIXDAEMON_FAILED,
		TOOLS_SERVICE_INIT_FAILED,
		TOOLS_SERVICE_FINISH_FAILED,
		TOOLS_SERVICE_START_FAILED,
		TOOLS_SERVICE_PARSEARGUMENTS_FAILED,
		TOOLS_SERVICE_ISINSTALLED_FAILED,
		TOOLS_SERVICE_INSTALL_FAILED,
		TOOLS_SERVICE_SETSTATUS_FAILED,
		TOOLS_SERVICE_UNINSTALL_FAILED,
		TOOLS_SERVICE_ONINSTALL_FAILED,
		TOOLS_SERVICE_ONUNINSTALL_FAILED,
		TOOLS_SERVICE_ONINIT_FAILED,
		TOOLS_SERVICE_ONSTART_FAILED,
		TOOLS_SERVICE_ONSTOP_FAILED,
		TOOLS_SERVICE_ONCONTINUE_FAILED,
		TOOLS_SERVICE_ONDEVICEEVENT_FAILED,
		TOOLS_SERVICE_ONHARDWAREPROFILECHANGE_FAILED,
		TOOLS_SERVICE_ONINTERROGATE_FAILED,
		TOOLS_SERVICE_ONNETBINDADD_FAILED,
		TOOLS_SERVICE_ONNETBINDDISABLE_FAILED,
		TOOLS_SERVICE_ONNETBINDENABLE_FAILED,
		TOOLS_SERVICE_ONNETBINDREMOVE_FAILED,
		TOOLS_SERVICE_ONPARAMCHANGE_FAILED,
		TOOLS_SERVICE_ONPAUSE_FAILED,
		TOOLS_SERVICE_ONPOWEREVENT_FAILED,
		TOOLS_SERVICE_ONSESSIONCHANGE_FAILED,
		TOOLS_SERVICE_ONSHUTDOWN_FAILED,
		TOOLS_SERVICE_APPENDSTARTSCRIPTCOMMAND_FAILED,
		TOOLS_SERVICE_APPENDSTOPSCRIPTCOMMAND_FAILED,
		TOOLS_SERVICE_APPENDSTATUSSCRIPTCOMMAND_FAILED,
		TOOLS_SERVICE_SERVICENOTINSTALLED,
		TOOLS_SERVICE_SERVICEALREADYINSTALLED,
		TOOLS_SERVICE_CURRENTRUNLEVELNOTFOUND,
		TOOLS_SERVICE_INSTALLSERVICEEXECUTECOMMANDFAILED,
		TOOLS_SERVICE_REMOVESERVICEEXECUTECOMMANDFAILED,
		TOOLS_SERVICE_STARTSERVICEEXECUTECOMMANDFAILED,
		TOOLS_SERVICE_STOPSERVICEEXECUTECOMMANDFAILED,
		TOOLS_SERVICE_RUNLEVELDIRECTORYLENGTHTOOSMALL,
		TOOLS_SERVICE_SERVICEALREADYINPAUSE,
		TOOLS_SERVICE_SERVICEALREADYSTOPPED,
		TOOLS_SERVICE_SERVICENOTINPAUSE,
		TOOLS_SERVICE_STOPFAILED,

		// common
		TOOLS_NEW_FAILED,
		TOOLS_SYSTEM_FAILED,
		TOOLS_FINDFIRST_FAILED,
		TOOLS_COCREATEINSTANCE_FAILED,
		TOOLS_SHELLLINK_QUERYINTERFACE_FAILED,
		TOOLS_SHELLLINK_GETPATH_FAILED,
		TOOLS_PERSISTFILE_LOAD_FAILED,
		TOOLS_GETCWD_FAILED,
		TOOLS_GETADDRINFO_FAILED,
		TOOLS_GETNAMEINFO_FAILED,
		TOOLS_STAT_FAILED,
		TOOLS_STATFS_FAILED,
		TOOLS_SPRINTF_FAILED,
		TOOLS_LSTAT_FAILED,
		TOOLS_FSTAT_FAILED,
		TOOLS_FCNTL_FAILED,
		TOOLS_MBSTOWCS_FAILED,
		TOOLS_WCSRTOMBS_FAILED,
		TOOLS_OPEN_FAILED,
		TOOLS_LSEEK_FAILED,
		TOOLS_READ_FAILED,
		TOOLS_READLINK_FAILED,
		TOOLS_CHMOD_FAILED,
		TOOLS_WRITE_FAILED,
		TOOLS_CLOSE_FAILED,
		TOOLS_OPENDIR_FAILED,
		TOOLS_CLOSEDIR_FAILED,
		TOOLS_UNLINK_FAILED,
		TOOLS_SYMLINK_FAILED,
		TOOLS_MKDIR_FAILED,
		TOOLS_RMDIR_FAILED,
		TOOLS_SETGID_FAILED,
		TOOLS_SETUID_FAILED,
		TOOLS_GZOPEN_FAILED,
		TOOLS_GZWRITE_FAILED,
		TOOLS_GETTIMEZONEINFORMATION_FAILED,
		TOOLS_GETTIMEOFDAY_FAILED,
		TOOLS_LOCALTIME_R_FAILED,
		TOOLS_LOCALTIME_FAILED,
		TOOLS_UNAME_FAILED,
		TOOLS_MOVEFILE_FAILED,
		TOOLS_WSASTARTUP_FAILED,
		TOOLS_WSACLEANUP_FAILED,
		TOOLS_WIDECHARTOMULTIBYTE_FAILED,
		TOOLS_OPENPROCESSTOKEN_FAILED,
		TOOLS_GETUSERPROFILEDIRECTORY_FAILED,
		TOOLS_MULTIBYTETOWIDECHAR_FAILED,
		TOOLS_OPENSCMANAGER_FAILED,
		TOOLS_CLOSESERVICEHANDLE_FAILED,
		TOOLS_CREATESERVICE_FAILED,
		TOOLS_GETDISKFREESPACE_FAILED,
		TOOLS_GETMODULEFILENAME_FAILED,
		TOOLS_OPENSERVICE_FAILED,
		TOOLS_DELETESERVICE_FAILED,
		TOOLS_SETSERVICESTATUS_FAILED,
		TOOLS_STARTSERVICECTRLDISPATCHER_FAILED,
		TOOLS_REGISTERSERVICECTRLHANDLEREX_FAILED,
		TOOLS_CONTROLSERVICE_FAILED,
		TOOLS_STARTSERVICE_FAILED,
		TOOLS_GETHOSTNAME_FAILED,
		TOOLS_ACTIVATION_WRONG,
		TOOLS_OPERATION_NOTALLOWED,


		// Insert here other errors...

		TOOLS_MAX_ERRORS

	} ;

	#ifdef WIN32
		// warning C4267: 'argument' : conversion from 'size_t' to 'long', possible loss of data

		#pragma warning (disable : 4267)
	#endif

	// declaration of class error
	dclCustomErrorClass (ToolsErrors, TOOLS_MAX_ERRORS)
   
#endif

