cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/ConnectionsManagerMessages.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/ConnectionsManagerMessages.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/Session.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/Session.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/ConnectionsManagerErrors.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/ConnectionsManagerErrors.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/BaseProcessor.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/BaseProcessor.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/BaseProcessor.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/BaseProcessor.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/ConnectionsManagerErrors.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/ConnectionsManagerErrors.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/CMSocketsPool.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/CMSocketsPool.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/CMProcessor.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/CMProcessor.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/CMProcessor.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/CMProcessor.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/Session.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/Session.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/ConnectionsManager/src/ConnectionsManagerService.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/ConnectionsManager/src/ConnectionsManagerService.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/Makefile.am /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/Makefile.am
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/SocketErrors.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/SocketErrors.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/ClientSocket.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/ClientSocket.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/ClientSocket.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/ClientSocket.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/SocketErrors.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/SocketErrors.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/SocketsPool.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/SocketsPool.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/Socket.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/Socket.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Socket/src/Socket.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Socket/src/Socket.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/WebToolsErrors.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/WebToolsErrors.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/WebUtility.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/WebUtility.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/WebUtility.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/WebUtility.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/HttpGetThread.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/HttpGetThread.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/HttpPostThread.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/HttpPostThread.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/HttpGetThread.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/HttpGetThread.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/WebToolsErrors.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/WebToolsErrors.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/WebTools/src/HttpPostThread.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/WebTools/src/HttpPostThread.h
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Tools/src/DateTime.cpp /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Tools/src/DateTime.cpp
cp /mydisk/7/DevelopmentWorkingArea/CatraLibraries/Tools/src/DateTime.h /mydisk/7/DevelopmentWorkingArea/Perforce/branches/Durian/XDM3/catralibraries-0063/Tools/src/DateTime.h
